LapaperieCompaniesBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: LapaperieCompaniesBundle:Default:index }

companie:
    pattern:  /companie
    defaults: { _controller: LapaperieCompaniesBundle:Companie:index }

companie_list:
    pattern:  /companie
    defaults: { _controller: LapaperieCompaniesBundle:Companie:index }

companie_show:
    pattern:  /companie/{id}/show
    defaults: { _controller: LapaperieCompaniesBundle:Companie:show }

companie_edit:
    pattern:  /companie/{id}/edit
    defaults: { _controller: LapaperieCompaniesBundle:Companie:edit }

companie_new:
    pattern:  /companie/new
    defaults: { _controller: LapaperieCompaniesBundle:Companie:new }

companie_create:
    pattern:  /companie/create
    defaults: { _controller: LapaperieCompaniesBundle:Companie:create }

companie_delete:
    pattern:  /companie/{id}/delete
    defaults: { _controller: LapaperieCompaniesBundle:Companie:delete }

companie_update:
    pattern:  /companie/{id}/update
    defaults: { _controller: LapaperieCompaniesBundle:Companie:update }

