parameters:
#    lapaperie_companies.example.class: Lapaperie\CompaniesBundle\Example

services:
#    lapaperie_companies.example:
#        class: %lapaperie_companies.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
