imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: en }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

services:
 twig.extension.text:
     class: Twig_Extensions_Extension_Text
     tags:
         - { name: twig.extension }


# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    #secure_controllers:  true
    secure_all_services: false

# Imagine Configuration (thumbnails creation)
avalanche_imagine:
    filters:
       companie_big:
           type:    thumbnail
           options: { size: [504,420], mode: outbound}
       companie:
           type:    thumbnail
           options: { size: [252,210], mode: outbound}
       companie_thumbnail:
           type:    thumbnail
           options: { size: [84,70], mode: outbound}
       action:
           type:    thumbnail
           options: { size: [352,293], mode: outbound}
       video_thumbnail:
           type:    thumbnail
           options: { size: [100,75], mode: outbound}
       illustration:
           type:    thumbnail
           options: { size: [352,320], mode: outbound}

#Doctrine Behaviours
stof_doctrine_extensions:
    default_locale: fr_FR
    orm:
        default:
            sluggable: true
