LapaperieFileUploadBundle:
    resource: "@LapaperieFileUploadBundle/Controller/"
    type:     annotation
    prefix:   /

LapaperiePagesBundle:
    resource: "@LapaperiePagesBundle/Controller/"
    type:     annotation
    prefix:   /

LapaperieDiffusionBundle:
    resource: "@LapaperieDiffusionBundle/Controller/"
    type:     annotation
    prefix:   /

LapaperieActionCulturelleBundle:
    resource: "@LapaperieActionCulturelleBundle/Controller/"
    type:     annotation
    prefix:   /

LapaperieNewsletterBundle:
    resource: "@LapaperieNewsletterBundle/Controller/"
    type:     annotation
    prefix:   /

LapaperieAdminBundle:
    resource: "@LapaperieAdminBundle/Resources/config/routing.yml"
    prefix:   /

LapaperieFocusBundle:
    resource: "@LapaperieFocusBundle/Controller"
    type:     annotation
    prefix:   /

LapaperieCompaniesBundle:
    resource: "@LapaperieCompaniesBundle/Controller"
    type:     annotation
    prefix:   /

LapaperieVideoBundle_home:
    resource: "@LapaperieVideoBundle/Controller"
    type:     annotation
    prefix:   /

LapaperieMainBundle:
    resource: "@LapaperieMainBundle/Resources/config/routing.yml"
    prefix:   /

LapaperieAgendaBundle:
    resource: "@LapaperieAgendaBundle/Controller"
    type:     annotation
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

#Avalanche / Imagine / Bundle
_imagine:
    resource: .
    type:     imagine

#Security Admin
login:
    pattern: /login
    defaults: {_controller: LapaperieAdminBundle:Admin:login }
login_check:
    pattern: /login_check
logout:
    pattern: /logout
