LapaperieCompaniesBundle:
    resource: "@LapaperieCompaniesBundle/Resources/config/routing.yml"
    prefix:   /

LapaperieVideoBundle:
    resource: "@LapaperieVideoBundle/Resources/config/routing.yml"
    prefix:   /videos

LapaperieMainBundle:
    resource: "@LapaperieMainBundle/Resources/config/routing.yml"
    prefix:   /

LapaperieAgendaBundle:
    resource: "@LapaperieAgendaBundle/Resources/config/routing.yml"
    prefix:   /agenda

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
