LapaperieCompaniesBundle:
    resource: "@LapaperieCompaniesBundle/Controller"
    type:     annotation
    prefix:   /

LapaperieVideoBundle:
    resource: "@LapaperieVideoBundle/Resources/config/routing.yml"
    prefix:   /videos

LapaperieMainBundle:
    resource: "@LapaperieMainBundle/Resources/config/routing.yml"
    prefix:   /

LapaperieAgendaBundle:
    resource: "@LapaperieAgendaBundle/Resources/config/routing.yml"
    prefix:   /agenda

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

#Avalanche / Imagine / Bundle
_imagine:
    resource: .
    type:     imagine
