parameters:
#    lapaperie_agenda.example.class: Lapaperie\AgendaBundle\Example

services:
#    lapaperie_agenda.example:
#        class: %lapaperie_agenda.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
