parameters:
    contact_email_from: contact@lapaperie.fr

services:
#    act_envcontact.example:
#        class: %act_envcontact.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    pagerfanta.view.default:
        class: Pagerfanta\View\DefaultView
        public: false
        tags: [{ name: pagerfanta.view, alias: default }]
    pagerfanta.view.adminView:
        class: Lapaperie\AdminBundle\pagerView
        arguments:
            - @pagerfanta.view.default
            - { proximity: 2, previous_message: Précédent, next_message: Suivant }
        public: true
        tags: [{ name: pagerfanta.view, alias: adminView }]

    lapaperie_newsletter.create_inscription:
        class: Lapaperie\NewsletterBundle\createInscription
        arguments:
            - @doctrine.orm.default_entity_manager
            - @mailer
            - %contact_email_from%
            - @templating
