<?php

namespace Lapaperie\AgendaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActualiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActualiteRepository extends EntityRepository
{
}