<?php

namespace Lapaperie\AgendaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActualiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActualiteRepository extends EntityRepository
{

    public function findHomeActualite()
    {
        $now = new \DateTime();

        return $this->getEntityManager()
            ->createQuery('SELECT a FROM LapaperieAgendaBundle:Actualite a
                           WHERE a.date_beginning > :now
                           ORDER BY a.date_beginning ASC
                           '
                       )->setParameter('now',$now)
            ->getResult();
    }

    public function findAllOrderByDateBeginning()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT a FROM LapaperieAgendaBundle:Actualite a
                           ORDER BY a.date_beginning DESC
                           '
                       )
            ->getResult();
    }

    public function findActiveActualiteByMonth(\DateTime $dateBeginning, \DateTime $dateEnd )
    {

        return $this->getEntityManager()
            ->createQuery('SELECT a FROM LapaperieAgendaBundle:Actualite a
                                   WHERE
                                   (
                                       (
                                           a.date_beginning >= :now
                                           AND
                                           a.date_beginning <= :end
                                       )
                                       OR
                                       (
                                           a.date_end >= :now
                                           AND
                                           a.date_end <= :end
                                       )
                                       OR
                                       (
                                           a.date_beginning <= :now
                                           AND
                                           a.date_end >= :end
                                       )
                                   )
                                   ORDER BY a.date_beginning ASC
                           '
                       )->setParameters(array('now' => $dateBeginning, 'end' => $dateEnd ))
                       ->getResult();
    }

    public function createQBfindAllOrderByDateBeginning()
    {
        return $this->createQueryBuilder('n')->add('orderBy', 'n.date_beginning DESC');
    }
}
