<?php

namespace Lapaperie\NewsletterBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SubscriberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscriberRepository extends EntityRepository
{
    public function findAllActive()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT s, i FROM LapaperieNewsletterBundle:Subscriber s
                           JOIN s.inscriptions i
                           WHERE i.date_confirmation IS NOT NULL
                           AND i.date_unscribe IS NULL
                           ORDER BY i.date_inscription ASC'
                       )
            ->getResult();
    }
}
