<?php

namespace Lapaperie\FocusBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FocusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FocusRepository extends EntityRepository
{
    /**
     * Met tous les focus à false sauf celui dont l'id est passé en argumebt
     *
     */
    public function setOthersOffLine(Focus $focusOnLine)
    {
        $focus = $this->findAll();
        foreach($focus as $foc) {
            if($foc != $focusOnLine){
                $foc->setIsOnLine(false);
            }
        }
    }
}
