<?php

namespace Lapaperie\ActionCulturelleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActionCulturelleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActionCulturelleRepository extends EntityRepository
{
}