<?php

namespace Lapaperie\ActionCulturelleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActionCulturelleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActionCulturelleRepository extends EntityRepository
{
    public function findAllOrderByYearDesc()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT  a FROM LapaperieActionCulturelleBundle:ActionCulturelle a
                ORDER BY a.year DESC'
            )
            ->getResult();
    }

    public function findAllNotPreviousYear()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT  a FROM LapaperieActionCulturelleBundle:ActionCulturelle a
                WHERE a.isPreviousYear = 0
                ORDER BY a.year ASC'
            )
            ->getResult();
    }
}
