LapaperieMainBundle_homepage:
    pattern:  /
    defaults: { _controller: LapaperieMainBundle:Main:index }

#ci-dessous routing provisoire pour avoir mes menus
LapaperieMainBundle_soutiencreation:
    pattern:  /soutien-creation
    defaults: { _controller: LapaperieMainBundle:Main:soutien }

LapaperieMainBundle_soutiencreation_ter:
    pattern:  /soutien-creation
    defaults: { _controller: LapaperieMainBundle:Main:soutien }

LapaperieMainBundle_soutiencreation_projets:
    pattern:  /soutien-creation
    defaults: { _controller: LapaperieMainBundle:Main:soutien }

LapaperieMainBundle_soutiencreation_solliciter:
    pattern:  /soutien-creation
    defaults: { _controller: LapaperieMainBundle:Main:soutien }

LapaperieMainBundle_actionculturelle:
    pattern:  /action-culturelle
    defaults: { _controller: LapaperieMainBundle:Main:culturelle }

LapaperieMainBundle_diffusioninfusion:
    pattern:  /diffusion-infusion
    defaults: { _controller: LapaperieMainBundle:Main:diffusion }

