LapaperieMainBundle_homepage:
    pattern:  /
    defaults: { _controller: LapaperieMainBundle:Main:index }

LapaperieMainBundle_homepage_paperie:
    pattern:  /la-paperie
    defaults: { _controller: LapaperieMainBundle:Main:paperie }

LapaperieMainBundle_homepage_cnar:
    pattern:  /la-paperie/cnar
    defaults: { _controller: LapaperieMainBundle:Main:cnar }

LapaperieMainBundle_homepage_partners:
    pattern: /la-paperie/equipe-partenaires
    defaults: { _controller: LapaperieMainBundle:Main:equipe }

LapaperieMainBundle_homepage_description:
    pattern: /la-paperie/description
    defaults: { _controller: LapaperieMainBundle:Main:description }

LapaperieMainBundle_homepage_formation:
    pattern: /la-paperie/formation
    defaults: { _controller: LapaperieMainBundle:Main:formation }

LapaperieMainBundle_soutiencreation:
    pattern:  /soutien-creation
    defaults: { _controller: LapaperieMainBundle:Main:soutien }

LapaperieMainBundle_soutiencreation_ter:
    pattern:  /soutien-creation/ter
    defaults: { _controller: LapaperieMainBundle:Main:ter }

LapaperieMainBundle_soutiencreation_projets:
    pattern:  /soutien-creation/projets
    defaults: { _controller: LapaperieMainBundle:Main:projets }
projet_show:
    pattern:  /soutien-creation/projets/{slug}
    defaults: { _controller: LapaperieMainBundle:Main:projet }

LapaperieMainBundle_soutiencreation_solliciter:
    pattern:  /soutien-creation/solliciter-residence
    defaults: { _controller: LapaperieMainBundle:Main:solliciter }

LapaperieMainBundle_actionculturelle:
    pattern:  /action-culturelle
    defaults: { _controller: LapaperieMainBundle:Main:culturelle }

LapaperieMainBundle_diffusioninfusion:
    pattern:  /diffusion-infusion
    defaults: { _controller: LapaperieMainBundle:Main:diffusion }

