LapaperieMainBundle_homepage:
    pattern:  /
    defaults: { _controller: LapaperieMainBundle:Main:index }

#ci-dessous routing provisoire pour avoir mes menus
LapaperieMainBundle_soutien_creation:
    pattern:  /soutien-creation
    defaults: { _controller: LapaperieMainBundle:Main:index }

LapaperieMainBundle_action_culturelle:
    pattern:  /action-culturelle
    defaults: { _controller: LapaperieMainBundle:Main:index }

LapaperieMainBundle_diffusion_infusion:
    pattern:  /diffusion-infusion
    defaults: { _controller: LapaperieMainBundle:Main:index }

