LapaperieMainBundle_homepage:
    pattern:  /
    defaults: { _controller: LapaperieMainBundle:Main:index }

#ci-dessous routing provisoire pour avoir mes menus
LapaperieMainBundle_test1:
    pattern:  /test1
    defaults: { _controller: LapaperieMainBundle:Main:index }

LapaperieMainBundle_test2:
    pattern:  /test2
    defaults: { _controller: LapaperieMainBundle:Main:index }

LapaperieMainBundle_test3:
    pattern:  /test3
    defaults: { _controller: LapaperieMainBundle:Main:index }

LapaperieMainBundle_test4:
    pattern:  /test4
    defaults: { _controller: LapaperieMainBundle:Main:index }

