<?php

namespace Lapaperie\VideoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 *  VideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class  VideoRepository extends EntityRepository
{
    public function findAllOrderByPublicationDateDesc()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT  a FROM LapaperieVideoBundle:Video a
                ORDER BY a.publicationDate DESC'
            )
            ->getResult();
    }
}
