<?php

namespace Lapaperie\CompaniesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ImageCompanieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageCompanieRepository extends EntityRepository
{
}
