<?php

namespace Lapaperie\CompaniesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * imageCompanieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class imageCompanieRepository extends EntityRepository
{
}