<?php

namespace Lapaperie\FileUploadBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FileUploadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileUploadRepository extends EntityRepository
{
}
